### ISSUE TITLE
Facebook auth fails

### ISSUE THREAD

**Issue by quanvo87** [gameontext/gameon#109]
`Was expecting a query string of the form 'access_token=XXX' or 'access_token=XXX&expires=YYY'`

It looks like the query string is actually in the form:

`'access_token:XXX&token_type:XXX&expires_in:XXX'`

**Comment by ebullient** [comment]
Good catch! We'd made a right mess of auth things a little bit ago... I think we forgot to wrap this one up. 

Have a look? (Liberty not spring, gradle build)
https://github.com/gameontext/gameon-auth/

https://github.com/gameontext/gameon-auth/blob/master/auth-app/src/main/java/org/gameontext/auth/facebook/FacebookCallback.java
