### ISSUE TITLE
kubectl doesn't show gameon deployments by default

### ISSUE THREAD

**Issue by kevinwlau** [gameontext/gameon#134]
The `go-run.sh` setup script sets the deployments' namespace to `gameon-system`.
By default, `kubectl` commands will run with the `default` namespace, so the commands (and minikube dashboard) show nothing about the gameon deployments.

**Fix**: Switch the namespace to `gameon-system` either by:

1. Changing the default namespace in the kubectl config with `kubectl config set-context minikube --namespace=gameon-system`

	- or making a new config? `kubectl config set-context minikube-gameon --cluster=minikube --user=minikube --namespace=gameon-system`

2. Appending `--namespace=gameon-system` to every `kubectl` and `minikube` commands

Alternatively, change the gameon namespace to use the `default` namespace instead of having its own namespace

**Comment by dshimo** [comment]
Messing with 1) seemed to mess up how `helm` finds its charts.

Could add to docs: to view these items on the kubernetes dashboard you must switch namespace to `gameon-system` in the left menu

**Comment by ebullient** [comment]
The intention was that you, the intrepid developer, would be writing your own additional services, which would then be in the default namespace for you to control.

If you could try the `iterate` branch (beware, I force-push that thing.. so you need to be prepared to hard reset periodically) , `go-run k .... ` will do the kubectl command with the gameon-system namespace

**Comment by dshimo** [comment]
The main issue was that we didn't know why Kubernetes didn't list our deployments and services when helm did. When the script handled these automatically we weren't aware it had neatly organized them for us. It's nice and I can agree now but the docs should at least mention this

**Comment by ebullient** [comment]
I can add that. Thanks for the feedback. I will add to the iterate branch, and you can close this once I've done the job to your liking. =)

**Comment by ebullient** [comment]
PR updated. Let me know what you think.

**Comment by dshimo** [comment]
looks good! 👍
