### ISSUE TITLE
docker-compose.yml references kafkaviewer/kafkaviewer-wlpcfg which is missing

### ISSUE THREAD

**Issue by curtinmjc** [gameontext/gameon#26]
- Following instructions in README.md.
- Successfully ran ./build.sh
- But problems with docker-compose build
- Specific error message... ERROR: build path /Users/curtinmjc/Git/gameon/kafkaviewer/kafkaviewer-wlpcfg either does not exist, is not accessible, or is not a valid URL.

- kafkaviewer is referenced in docker-compose.yml as result of recent commit but is missing from repo

**Comment by BarDweller** [comment]
I've updated the main docker-compose to remove kafkaviewer .. which is a kind of optional utility for viewing the messages flying around inside game-on. It's not a required part of game-on to use when developing or running game-on, but ended up as part of the main docker-compose while we were considering adding it as one of the core game-on services.. oops. 

All should be good now =) If you actually want to run kafkaviewer, there are instructions over in it's readme that should help get it up and running..
