### ISSUE TITLE
Progress but had to do "docker-compose pull" and had issue with Google authentication

### ISSUE THREAD

**Issue by curtinmjc** [gameontext/gameon#28]
Changes that were made to remove kafkaviewer allowed for further progress but then other things cropped up

1.  $ docker-compose build -- does not work... cmd finishes almost immediately with lots of "skipping" messages (e.g. player uses an image, skipping)
2.  I thought above issue related to docker-compose.yml file specifying image rather than build (e.g. image: gameontext/gameon-player
3.  so... I ran $ docker-compose pull
4.  result... many, many minutes of image downloads
5.  then ran $ docker-compose up and system appeared to be running
6.  since my docker machine URL = 192.168.99.100 I ran following in browser with success:  192.168.99.100/#/... hooray
7.  in this Gameon UI I clicked "Enter" and selected Google for authentication but that's when my luck ran out... result was the following browser error message:

Error 404: javax.servlet.UnavailableException: SRVE0319E: For the [net.wasdev.gameon.auth.google.GoogleAuth] servlet, net.wasdev.gameon.auth.google.GoogleAuth servlet class was found, but a resource injection failure has occurred. CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/net.wasdev.gameon.auth.google.GoogleAuth/key reference. The exception message was: CWNEN1003E: The server was unable to find the googleOAuthConsumerKey binding with the java.lang.String type for the java:comp/env/net.wasdev.gameon.auth.google.GoogleAuth/key reference.

**Comment by BarDweller** [comment]
That's totally expected for local, we don't share our Google /Facebook/etc secret keys.. you can use the anonymous login when running locally or register your own apps and add their keys to game-on.env

Docker compose build should pull any image it needs..with the final ones obtained during up

May want to check what version of docker compose you have..

**Comment by curtinmjc** [comment]
I tried again starting with "docker-compose up" and then logging in as anonymous, and the game worked fine.  However, I still say that "docker-compose build" did not work previously.  Instead I had to do "docker-compose pull" which did create the environment that I am now using locally.

**Comment by ebullient** [comment]
You know.. I've had to work on getting the betas set up properly, etc.

I am guessing this would work to combine the steps: `docker-compose build --pull`

I will update the instructions accordingly

**Comment by ebullient** [comment]
Can you review @curtinmjc ?
