### ISSUE TITLE
What's the difference between "examine" and "look"?

### ISSUE THREAD

**Issue by Tom-Banks** [gameontext/gameon#73]
Why is there the "look" command for looking at the contents of a room, and an "examine" command for looking at given objects? Surely "/examine room" should do the same as "/look" and "/look object" should do the same as "/examine object" - there doesn't seem to be much distinction on why one command only works for some objects and not others (looking at a room as an object).

**Comment by ebullient** [comment]
This also varies from room to room. I will simplify the help, though it would be up to the room how to handle the two commands (to treat them the same or not)
