### ISSUE TITLE
No parameters on command hints in "help"

### ISSUE THREAD

**Issue by Tom-Banks** [gameontext/gameon#74]
When typing "/help" I can see a list of possible commands - some of these such as /look don't require additional parameters, but some do. It would be helpful if /help also listed optional/required parameters for each of the commands. 

It would also be additionally useful if I entered a command which requires an additional parameter that it would tell me that an extra parameter is required - if I type "/examine" I get the error "I'm sorry, but I'm not sure how I'm supposed to examine" - it would be great if the error said "I'm sorry I don't know how to examine nothing - try /examine <item> to examine an object" or something like that - would make it easier to understand why a command didn't work.

**Comment by ebullient** [comment]
/help is very general, and supplies only the information provided by the room. It isn't possible for the central thing (the mediator or the UI alone in some cases) to provide object-level help: it is up to the room to provide it.
