### ISSUE TITLE
Not clear when a room is down

### ISSUE THREAD

**Issue by Tom-Banks** [gameontext/gameon#76]
After wondering why I had encountered 3 rooms all seeming to be themed around an unwell person it's now appearing that "the room is unwell" themed messages are indicating that a room is actually down? It's not clear if that's the case, as the first couple of rooms that gave those messages had me trying to interact with them and try to solve some sort of puzzle that wasn't there.

**Comment by ebullient** [comment]
Will clarify the message, but the sickRoom is (by nature) a stand in for a room it can't contact (hence visible retry). And yes, it is a puzzle... but it's a consistent puzzle for all rooms
