### ISSUE TITLE
Enable MicroProfile in Player, Auth, Mediator, Map, Room

### ISSUE THREAD

**Issue by animeshsingh** [gameontext/gameon#92]
These Java microservices need to explicitly use the MicroProfile framework

**Comment by ilanpillemer** [comment]
Why do they need to?

**Comment by animeshsingh** [comment]
I was told @ebullient said so would suffice :-) But essentially we want to make a case that we are following MicroProfile purely for these, and take GameOn to the developers in that community

**Comment by ebullient** [comment]
they already do -- it just isn't obvious.

**Comment by ebullient** [comment]
They're all flipped to OpenLiberty now.
Won't take much to switch the features being included.
