### ISSUE TITLE
Migrate system to k8s + istio

### ISSUE THREAD

**Issue by ebullient** [gameontext/gameon#96]
- [x] Move root repo updates into travis builds
- [ ] Build linkage: 
  - [x] Automatic Docker build for base liberty image
  - [x] Scripts for starting/stopping system for k8s + istio
  - [ ] Webhook to trigger Travis builds for dependent images

**Comment by rshriram** [comment]
ping?
Now that we have WebSocket support, the last hurdle has also been removed I hope. If you migrate, we could potentially involve different aspects of Istio in the Game.

**Comment by ebullient** [comment]
we're working on it.. I've just streamlined & stripped down to a basic docker compose end to end flow: amalgam8 is out. K8s is next, and yes. Istio. And I would love the help.

**Comment by AnthonyAmanse** [comment]
@ebullient What's the status on this one? There is a published pattern that's currently broken https://developer.ibm.com/code/patterns/deploy-java-microservices-on-kubernetes-with-polyglot-support/

**Comment by BarDweller** [comment]
Afaik, there's not been any change on this since the sep17th update, because we've not had time to look at this, due our our priorities dictating that our efforts should be made toward other items. We'd love to get this done though, if we can figure out how to fit it into our other goals.

**Comment by BarDweller** [comment]
Dropped a first pass at k8s support last week, tested on minikube & icp, no docs yet, ping me on slack if you want to try it out until I get the helm chart complete and get the docs updated.

**Comment by ebullient** [comment]
istio .. sort of works. Ran smack into WebSocket stuff at a very inconvenient time.. would love quick help & sanity checking.

**Comment by ebullient** [comment]
As of #130, Kubernetes + istio (1.0) works (need verification with IKS)
